### ISSUE TITLE
Add Icons to menu UI

### ISSUE THREAD

**Issue by claudds** [jacobrs/Signal-Android#123]
Add in the icons to their appropriate UI places

Ideal hours: 4 hours
Related story: #90

**Comment by lori-dalkin** [comment]
Found the proper area to inflate the menu context and set an items icon visibility to true  for the Conversation Activity with @BDSchoeler 
Researching the proper way to add toggle the icon visibility took longer than expected due to the innate way android handles action bars and menu.

Time spent: 3 hours
