### ISSUE TITLE
Test the delete function with swiping.

### ISSUE THREAD

**Issue by BDSchoeler** [jacobrs/Signal-Android#24]
Implement test code to test that the conversation is properly deleted, or that the method is properly called.

Ideal Hours: 3 hours
Related Stories: #9

**Comment by BDSchoeler** [comment]
The thread database class is responsible for the storage of conversation threads. It has a deleteConversation method that can be used to delete the converstation. This is the method that we will need to call.

**Comment by lori-dalkin** [comment]
Attempted an espresso test for this functionality.
Testing UI features may prove to be unfeasible due to the lack of existing testing framework within the code base. Specifically for swiping to delete, we cannot extract our code since it is done within a private inner class that has private dependencies. Furthermore, when trying to test with Espresso, a valid phone number along with a verification code is needed to set up the application and run a test. This is cannot be automated.  Moreover it looked as if swipe actions aren't even detected with Espresso.

These issues were brought up in our TA meeting.

Research done with @BDSchoeler 
Time Spent: 5 hours
