### ISSUE TITLE
Implement Compression for Outgoing Attachments

### ISSUE THREAD

**Issue by claudds** [jacobrs/Signal-Android#47]
Using the library obtained through research, implement compression for outgoing attachments.

Ideal Hours: 5 hours
Related Story: #34

**Comment by samantha-kerr** [comment]
Implemented the compressVideo method from the SiliCompressor library to compress a video attachment with video attachment URI and a test location as parameters; the current location stored within the existing attachment is null, and so a temporary value " " is being passed into the compressVideo method for testing purposes. As it stands, this issue is preventing the video from being compressed. 

Attempting to return a new attachment with an updated location to the compressed video; created the method updateAttachmentLocation in AttachmentDatabase class to take an attachment and a (string) location and return a new DatabaseAttachment with the existing attachment parameters with the new location value. 

Time spent: 3 hours

**Comment by BDSchoeler** [comment]
This commit made the video compression function for signal and text messages. Should add better error handling and validation
https://github.com/jacobrs/Signal-Android/commit/bf4ead8646a1c5802ca68b716e1d5071434b0130
