### ISSUE TITLE
Find a Way to Bypass phone number registration

### ISSUE THREAD

**Issue by claudds** [jacobrs/Signal-Android#58]
The application currently requires you to register your phone number in order to continue to normal application usage. This hinders automated acceptance tests as there are no known test phone numbers; need to find a way to bypass this registration.

Ideal Hours: 5h.
Related Story: #56

**Comment by benrs** [comment]
For this subtask there were three choices to choose from, some which do not really satisfy the subtask:

1. Simply use our own phone number to verify the emulated phone. That or run all espresso tests on our personal phones so that we do not need to re-verify every single time. Pros: It works and doesn't cause any problems, and it allows us to run espresso tests. Cons: It does not fulfill the story of finding a way to bypass the registration.

2. Host a mock server either locally or on a server. Pros: Would allow us to mock calls and bypass registration. Cons: Scope of work is too large. The current system doesn't have anything in place to support switching out the backend, so we would have to intercept or redirect the call through some other configuration, not ideal.

3. Add code in the registration module/activity that will check if we are running tests, currently we check to see if the espresso class exists in our current build (the test build is separate from the android build), but ideally it would be a flag. Pros: It satisfies the solution and allows us to skip the verification/registration. Cons: Every time we re-install the apk we will have to run the espresso test which allows us to skip registration, also it is not completely automated because there are some native elements that espresso can not detect. Another con is we are adding checks in the code to see if we're currently testing, which is mixing android code with testing code.

In an ideal situation Signal would have created a way to skip verification so that all other components can be tested with some mock data. Sadly this is not the case. For that reason the next best solution would be to simply go with choice number 1, but as per my team mates we still wanted a way to bypass verification/registration so I added some code which follow choice number 3.

Hours Spent: 3h.
