### ISSUE TITLE
Implement Espresso Tests for Sprint 3 Stories

### ISSUE THREAD

**Issue by claudds** [jacobrs/Signal-Android#77]
As a developer, I want to have end-to-end espresso tests for all of my previously implemented features in order to ensure UI for these features is working correctly.

- [x] Mark Message as Unread #78 
- [x] Pin Messages #79 
- [x] Automatic Permission Granting in fake verification test #80

Priority: 4/4
Risk: 2/4
Story Points: 1

# Acceptance Tests
Testing Component | Inputs | Outputs | Status
------ | ------- | --------- | --------
Automating Fake Verify| Run fake verify espresso test and let it run | Fake verified phone  | PASS
Pinning Message Tests | Run Pinning Messages Tests | All tests should pass | PASS
Mark Message as Unread Tests | Run Mark Message as Unread Tests | All tests should pass | PASS

**Comment by benrs** [comment]
Finished fixing the fake verify, this involved adding a way to bypass the native dialogs for accepting permissions, it also involved adding a new library for similar logs, finally it also involved writing util classes for actions and expectations so that it's easier for everyone else to write ui tests. PR is #98.
